version: 2.1
jobs:
  build:
    docker:
    - image: cimg/base:stable
    steps:
    - run:
        name: Checkout via HTTPS
        command: git clone --branch "$CIRCLE_BRANCH" https://github.com/MidnightBSD/raphael.git .
    - run:
        name: Install dependencies
        command: |
          sudo apt-get update
          sudo apt-get install -y cmake xvfb valac libwebkit2gtk-4.1-dev libsoup-3.0-dev libgcr-3-dev libpeas-dev libsqlite3-dev libjson-glib-dev libarchive-dev intltool libxml2-utils
    - run:
        name: Build
        command: |
          mkdir _build
          cd _build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make
    - run:
        name: Virtual framebuffer
        command: Xvfb :99 -screen 0 1280x1024x24
        background: true
    - run:
        name: Run unit tests
        command: |
          cd _build
          make check
    - run:
        name: Install system-wide
        command: |
          cd _build
          sudo make install
  snap:
    docker:
    - image: snapcore/snapcraft:stable
    steps:
    - run:
        name: Checkout via HTTPS
        command: git clone --branch "$CIRCLE_BRANCH" https://github.com/MidnightBSD/raphael.git .
    - run:
        name: Refresh package cache
        command: |
          apt-get update
    - run:
        name: Build snap
        command: snapcraft

workflows:
  version: 2
  ci:
    jobs:
    - build
    - snap
